# 2 March Assignment 2


### Q1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files. Delete the found duplicate file. [Hint: use hashlib]


In [36]:
import hashlib
import os

def scanDuplicates(path):
    dirList = os.listdir(path)

    hashList = []
    duplicate = []
    pathDirDict = {path : dirList}


    for i in dirList:
        if '.' not in i:
            pathDirDict[path + '\\' +  i] = os.listdir(path + '\\' + i)

    for i in pathDirDict:
        for j in pathDirDict[i]:
            if '.txt' in j:

                fileObj = open(i + '\\' + j)

                str1 = fileObj.read().encode()

                hash1 = hashlib.sha256(str1)

                if hash1.hexdigest() in hashList:
                    duplicate.append(i + '\\' + j)
                else:
                    hashList.append(hash1.hexdigest())

                fileObj.close()
                
    return duplicate

def removeDuplicate(duplicate):
    for i in duplicate:
        os.remove(i)
    print("Duplicates Remvoed!")
    

path = input("Enter path of the first file: ")

duplicates = scanDuplicates(path)

print("Duplicates:", duplicates)

removeDuplicate(duplicates)

print("Duplicates Remaining:", scanDuplicates(path))


Enter path of the first file: C:\Users\saijain\Downloads
Duplicates: ['C:\\Users\\saijain\\Downloads\\CatalystTraining\\test3 - Copy.txt', 'C:\\Users\\saijain\\Downloads\\Notes\\test3 - Copy.txt']
Duplicates Remvoed!
Duplicates Remaining: []


### Q2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]


In [38]:
import random
import string

password = []

for i in range(0, 2):
    password.append(random.choice(string.ascii_lowercase))
    password.append(random.choice(string.digits))
password.append(random.choice(string.ascii_uppercase))
password.append(random.choice(string.punctuation))

random.shuffle(password)

print("".join(password))

s13Tv#


### Q3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [39]:
import numpy as np
import math

def isPrime(num):
    a=2
    while a<=math.sqrt(num):
        if num%a<1:
            return False
        a=a+1
    return num>1

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of cols: "))

arr = np.arange(0, (rows*cols)).reshape(rows, cols)

for i in range(rows):
    for j in range(cols):
        num = arr[i][j]
        if isPrime(num):
            arr[i][j] = num**3
            
print(arr)

Enter the number of rows: 7
Enter the number of cols: 7
[[     0      1      8     27      4    125      6]
 [   343      8      9     10   1331     12   2197]
 [    14     15     16   4913     18   6859     20]
 [    21     22  12167     24     25     26     27]
 [    28  24389     30  29791     32     33     34]
 [    35     36  50653     38     39     40  68921]
 [    42  79507     44     45     46 103823     48]]


### Q4.	Python program to get the sum of every cubed value and its previous integer. 

In [40]:
number = 0
arr2 = np.empty_like(arr)
for i in range(rows):
    for j in range(cols):
        if number != 0 and ((arr[i][j]/number)/number) == number:
            arr2[i][j] = arr[i][j] + arr[i][j-1]
        else:
            arr2[i][j] = arr[i][j]
        number += 1
            
print(arr2)

[[     0      1      9     35      4    129      6]
 [  2540      8      9     10   1341     12   2209]
 [    14     15     16   4929     18   6877     20]
 [    21     22  12189     24     25     26     27]
 [    28  24417     30  29821     32     33     34]
 [    35     36  50689     38     39     40  68961]
 [    42  79549     44     45     46 103869     48]]


### Q5.	Given two arrays, find their intersection. Examples:

### Input:

### arr1[] = [1, 3, 4, 5, 7]
### arr2[] = [2, 3, 5, 6]


In [41]:
import numpy as np

arr1 = np.array([1, 3, 4, 5, 7])
arr2 = np.array([2, 3, 5, 6])

arrInter = np.intersect1d(arr1, arr2)

print(arrInter)

[3 5]


### Q6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [42]:
arr = np.arange(7, (7*49)+1, 7).reshape(7, 7)
print(arr)
print("\n\nLast Element of the array:", arr[-1][-1])


[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]


Last Element of the array: 343


### Q7.	Checker Board Patten using Numpy:
### [   1   0   1   0   1   0   1
### 0   1   0   1   0   1   0
### 1   0   1   0   1   0   1
### 0   1   0   1   0   1   0
### 1   0   1   0   1   0   1  ]


In [43]:
import numpy as np
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of cols: "))

arr = np.zeros((rows, cols), dtype = 'int8')

arr[1::2, 1::2] = 1
arr[0::2, 0::2] = 1

print(arr)

Enter number of rows: 7
Enter number of cols: 7
[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


### Q8.	Create a given Matrix:
### [  A,     B,     C,       D
### E,      F,     G,       H
### I,      a,      K,       L
### M,    N,     o,       P
### Q,     R,      S,       T
### U,     0,     W,      O ]

### Replace all the vowels by np.nan
### A, E, I, O U  -- >  np.nan
### Return the count of the missing values


In [44]:
import string
list1 = list(string.ascii_uppercase)[:-2]
array = np.array(list1).reshape(4, 6)
list1 = array.tolist()
vowels = ['A', 'E', 'I', 'O', 'U']
for i in range(0, len(list1)):
    list1[i] = [np.nan if item in vowels else item for item in list1[i]]
    
sum = 0
for i in list1:
    sum += i.count(np.nan)
    
print(sum)

5
